version: '3.8'
services:
  vprodb:
    build:
      context: ./Docker-file/db
    image: akaxyz/mydb
    container_name: mydb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprobdpass

  vprocache01:
    image: memcached
    ports:
      - "11211:11211"

  vpromq01:
  image: rabbitmq
  ports:
    - "15672:15672"
  environment:
    - RABBITMQ_DEFAULT_USER=guest
    - RABBITMQ_DEFAULT_PASS=guest

  vproapp:
    build:
      context: ./Docker-file/app
    image: akaxyz/myapp
    container_name: myapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps

  vproweb:
    build:
      context: ./Docker-file/app
    image: akaxyz/myweb
    container_name: myweb
    ports:
      - "80:80"

volumes:
  vprodbdata: {}
  vproappdata: {}
  
